USE codeup_test_db;
INSERT INTO albums (artist, name, release_date, sales, genre)
    VALUES ('Various artists', 'Grease: The Original Soundtrack', '1978', 38,
            'Soundtrack'),
      ('Led Zeppelin',	'Led Zeppelin IV',	'1971',	37, 'Heavy metal'),
      ('Michael Jackson',	'Bad',	'1987', 35,	'Pop, Funk, Rock'),
      ('Alanis Morissette',	'Jagged Little Pill',	'1995', 24.4,	'Alternative rock'),
      ('Shania Twain',	'Come On Over',	'1997', 33,	'Country, Pop'),
      ('Celine Dion',	'Falling into You',	'1996', 20.2,	'Pop, Soft rock'),
      ('The Beatles',	'Sgt. Pepper''s Lonely Hearts Club Band',	'1967', 32,	'Rock'),
      ('Eagles',	'Hotel California',	'1976',	21.5, 'Rock, Soft rock, Folk rock'),
      ('Various artists',	'Dirty Dancing', '1987', 17.9,	'Pop, Rock, R&B'),
      ('Adele',	'21',	'2011', 25.3,	'Pop, Soul'),
      ('Celine Dion',	'Let''s Talk About Love',	'1997', 19.3,	'Pop, Soft rock'),
      ('The Beatles',	'1',	'2000', 22.6,	'Rock'),
      ('Michael  Jackson',	'Dangerous',	'1991',	16.3, 'Rock, Funk, Pop'),
      ('Madonna', 'The Immaculate Collection',	'1990', 19.4,	'Pop, Dance'),
      ('The Beatles',	'Abbey Road',	'1969', 14.4,	'Rock'),
      ('Bruce Springsteen',	'Born in the U.S.A.',	'1984', 19.6,	'Rock'),
      ('Dire Straits',	'Brothers in Arms',	'1985',	17.7, 'Rock, Pop'),
      ('James Horner',	'Titanic: Music from the Motion Picture',	'1997', 18.1,
      'Soundtrack'),
      ('Metallica',	'Metallica',	'1991', 21.2, 'Thrash metal, Heavy metal'),
      ('Nirvana',	'Nevermind',	'1991',	16.7, 'Grunge, Alternative rock'),
      ('Pink Floyd',	'The Wall',	'1979',	17.6, 'Progressive rock'),
      ('Santana',	'Supernatural',	'1999',	20.5, 'Rock'),
      ('Guns N'' Roses',	'Appetite for Destruction',	'1987',	21.6, 'Hard rock');